spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database:3306/${WT_DATABASE_NAME:database}?allowPublicKeyRetrieval=true&useSSL=false
    username: ${WT_DATABASE_USERNAME:username}
    password: ${WT_DATABASE_PASSWORD:password}
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: admin
      password: admin

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  web:
    resources:
      cache:
        period: 0

  mvc:
    static-path-pattern: /public/**
    hiddenmethod:
      filter:
        enabled: true