spring:
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: admin
      password: admin

  web:
    resources:
      static-locations: classpath:/resources/static
      cache:
        period: 0